image: clangbuiltlinux/ubuntu

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - ./build.sh

unit-test-job:
  stage: test
  script:
    - ./monkey_test.exe
