image: rsmmr/clang

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - ./build.sh

unit-test-job:
  stage: test
  script:
    - ./build.sh
    - valgrind --leak-check=full ./monkey_test.exe
