@echo OFF
REM This file is automatically generated with: tup generate build.bat
set tup_vardict=%cd%\tup-generate.vardict
cd "src/vec/src"
(gcc -Wall -Wextra -Wpedantic -Werror=implicit-function-declaration -std=c99 -g3 -fsanitize=address,undefined -I ../../../inc -c vec.c -o vec.o)
cd "../../sds"
(gcc -Wall -Wextra -Wpedantic -Werror=implicit-function-declaration -std=c99 -g3 -fsanitize=address,undefined -I ../../inc -c sds.c -o sds.o)
cd "../monkey_test"
(gcc -Wall -Wextra -Wpedantic -Werror=implicit-function-declaration -std=c99 -g3 -fsanitize=address,undefined -I ../../inc -c test_lexer.c -o test_lexer.o)
cd "../libmonkey"
(gcc -Wall -Wextra -Wpedantic -Werror=implicit-function-declaration -std=c99 -g3 -fsanitize=address,undefined -I ../../inc -c lexer.c -o lexer.o)
(gcc -Wall -Wextra -Wpedantic -Werror=implicit-function-declaration -std=c99 -g3 -fsanitize=address,undefined -I ../../inc -c token.c -o token.o)
cd "../.."
(ar rcs libmonkey.a src/libmonkey/lexer.o src/libmonkey/token.o)
(ar rcs libsds.a src/sds/sds.o)
(ar rcs libvec.a src/vec/src/vec.o)
(gcc -fsanitize=address,undefined src/monkey_test/test_lexer.o -o monkey_test.exe -L. -lmonkey -lsds -lvec)
