#! /bin/sh -ex
# This file is automatically generated with: tup generate build.sh
export tup_vardict="$(cd $(dirname $0) && pwd)/tup-generate.vardict"
cd "src/vec/src"
(clang -Wall -Wextra -Wpedantic -Werror=implicit-function-declaration -Werror=return-type -std=c99 -g3 -I ../../../inc -c vec.c -o vec.o)
cd "../../monkey_repl"
(clang -Wall -Wextra -Wpedantic -Werror=implicit-function-declaration -Werror=return-type -std=c99 -g3 -I ../../inc -c main.c -o main.o)
(clang -Wall -Wextra -Wpedantic -Werror=implicit-function-declaration -Werror=return-type -std=c99 -g3 -I ../../inc -c repl.c -o repl.o)
cd "../libmonkey"
(clang -Wall -Wextra -Wpedantic -Werror=implicit-function-declaration -Werror=return-type -std=c99 -g3 -I ../../inc -c ast.c -o ast.o)
(clang -Wall -Wextra -Wpedantic -Werror=implicit-function-declaration -Werror=return-type -std=c99 -g3 -I ../../inc -c lexer.c -o lexer.o)
(clang -Wall -Wextra -Wpedantic -Werror=implicit-function-declaration -Werror=return-type -std=c99 -g3 -I ../../inc -c parser.c -o parser.o)
(clang -Wall -Wextra -Wpedantic -Werror=implicit-function-declaration -Werror=return-type -std=c99 -g3 -I ../../inc -c token.c -o token.o)
cd "../monkey_test"
(clang -Wall -Wextra -Wpedantic -Werror=implicit-function-declaration -Werror=return-type -std=c99 -g3 -I ../../inc -c test.c -o test.o)
(clang -Wall -Wextra -Wpedantic -Werror=implicit-function-declaration -Werror=return-type -std=c99 -g3 -I ../../inc -c test_lexer.c -o test_lexer.o)
(clang -Wall -Wextra -Wpedantic -Werror=implicit-function-declaration -Werror=return-type -std=c99 -g3 -I ../../inc -c test_parser.c -o test_parser.o)
cd "../libhash"
(clang -Wall -Wextra -Wpedantic -Werror=implicit-function-declaration -Werror=return-type -std=c99 -g3 -I ../../inc -c fnv.c -o fnv.o)
(clang -Wall -Wextra -Wpedantic -Werror=implicit-function-declaration -Werror=return-type -std=c99 -g3 -I ../../inc -c hash.c -o hash.o)
cd "../sds"
(clang -Wall -Wextra -Wpedantic -Werror=implicit-function-declaration -Werror=return-type -std=c99 -g3 -I ../../inc -c sds.c -o sds.o)
cd "../.."
(llvm-ar rcs libmonkey.a src/libmonkey/ast.o src/libmonkey/lexer.o src/libmonkey/parser.o src/libmonkey/token.o)
(llvm-ar rcs libsds.a src/sds/sds.o)
(llvm-ar rcs libvec.a src/vec/src/vec.o)
(llvm-ar rcs libhash.a src/libhash/fnv.o src/libhash/hash.o)
(clang  src/monkey_repl/main.o src/monkey_repl/repl.o -o monkey_repl.exe libmonkey.a libsds.a libvec.a libhash.a)
(clang  src/monkey_test/test.o src/monkey_test/test_lexer.o src/monkey_test/test_parser.o -o monkey_test.exe libmonkey.a libsds.a libvec.a libhash.a)
