@echo OFF
REM This file is automatically generated with: tup generate build.bat
set tup_vardict=%cd%\tup-generate.vardict
cd "src/vec/src"
(cl -W3 -I ../../../inc -c vec.c -Fovec.o)
cd "../../sds"
(cl -W3 -I ../../inc -c sds.c -Fosds.o)
cd "../monkey_test"
(cl -W3 -I ../../inc -c test_lexer.c -Fotest_lexer.o)
cd "../libmonkey"
(cl -W3 -I ../../inc -c lexer.c -Folexer.o)
(cl -W3 -I ../../inc -c token.c -Fotoken.o)
cd "../.."
(lib /OUT:libmonkey.a src/libmonkey/lexer.o src/libmonkey/token.o)
(lib /OUT:libsds.a src/sds/sds.o)
(lib /OUT:libvec.a src/vec/src/vec.o)
(link src/monkey_test/test_lexer.o /OUT:monkey_test.exe /LIBPATH:. libmonkey.a libsds.a libvec.a)
