name: CI
on: [push]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get install build-essential
      - run: ./build.sh
      - run: ./monkey_test.exe
